# Generated by Django 5.0.4 on 2024-06-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filière',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matière',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=300)),
                ('birth_and_place', models.CharField(max_length=300)),
                ('nom_pere', models.CharField(max_length=150)),
                ('nom_mere', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=250)),
                ('sexe', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=200)),
                ('affecte', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classe_associée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_classe', to='gestion.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='gestion.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Frais_scolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.CharField(default=0, max_length=150)),
                ('montant_paye', models.CharField(default=0, max_length=150)),
                ('montant_restant', models.CharField(default=0, max_length=150)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_solde', to='gestion.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('coefficient', models.CharField(max_length=2)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classe_associée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluatuion_classe', to='gestion.classe')),
                ('matière_associée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluatuion_matiere', to='gestion.matière')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='matière_associée',
            field=models.ManyToManyField(blank=True, related_name='classe_matière', to='gestion.matière'),
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('frais_scolaire', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('filiere_associée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='gestion.filière')),
            ],
        ),
        migrations.CreateModel(
            name='Frais_niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_af', models.CharField(default=900000, max_length=150)),
                ('montant_non_af', models.CharField(default=1200000, max_length=150)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_niveau', to='gestion.niveau')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau_associée',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_niveau', to='gestion.niveau'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=150)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_note', to='gestion.etudiant')),
                ('evaluation_associee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evaluatuion_note', to='gestion.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(default=0)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_paiement', to='gestion.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=300)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('matière_associée', models.ManyToManyField(blank=True, related_name='professeur_matière', to='gestion.matière')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere_classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='gestion.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_matiere', to='gestion.matière')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_prof', to='gestion.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='Professeur_associée',
            field=models.ManyToManyField(blank=True, related_name='classe_professeur', to='gestion.professeur'),
        ),
    ]
