# Generated by Django 5.0.4 on 2024-06-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='classe',
            new_name='classe_id',
        ),
    ]
